name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Debug Cypress Installation
        run: ls -l node_modules/.bin/

      - name: Fix Cypress Permissions
        run: chmod +x node_modules/.bin/cypress

      - name: Install Cypress Globally
        run: npm install -g cypress

      - name: Run Cypress Tests
        run: npx --no-install cypress run --browser chrome --headless --spec "cypress/e2e/*.cy.js"

      - name: Upload Cypress Test Results (Screenshots/Videos)
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: |
            cypress/screenshots
            cypress/videos
          if-no-files-found: ignore
